# Generated by Django 6.0.6 on 2026-07-02 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام غذا")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("price", models.PositiveIntegerField(verbose_name="قیمت")),
                (
                    "is_vegetarian",
                    models.BooleanField(default=False, verbose_name="گیاهی"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="دسته\u200cبندی"
                    ),
                ),
            ],
            options={
                "verbose_name": "غذای منو",
                "verbose_name_plural": "غذاهای منو",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="تاریخ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="menus",
                        to="canteen.menuitem",
                        verbose_name="آیتم\u200cهای منو",
                    ),
                ),
            ],
            options={
                "verbose_name": "منوی روزانه",
                "verbose_name_plural": "منوهای روزانه",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="کد رهگیری",
                    ),
                ),
                ("first_name", models.CharField(max_length=120, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="نام خانوادگی"),
                ),
                (
                    "student_id",
                    models.CharField(max_length=50, verbose_name="شماره دانشجویی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("confirmed", "تایید شده"),
                            ("canceled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت سفارش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان ثبت سفارش"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        to="canteen.menuitem", verbose_name="غذاهای سفارش داده شده"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="canteen.menu",
                        verbose_name="منو",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
