# Generated by Django 6.0.6 on 2026-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام مخلفات")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="قیمت")),
            ],
            options={
                "verbose_name": "مخلفات",
                "verbose_name_plural": "مخلفات",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                editable=False, max_length=20, unique=True, verbose_name="کد رهگیری"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="extras",
            field=models.ManyToManyField(
                blank=True,
                related_name="orders",
                to="canteen.extra",
                verbose_name="مخلفات",
            ),
        ),
    ]
